# Site settings
title: ActiveMQ
email:
author:
description:
        url: http://apache.activemq.org

# Build settings
permalink: :title/
sass:
  sass_dir: css/

defaults:
  - scope:
      path: "assets/img"
    values:
      image: true
