# Site settings
title: ActiveMQ
email:
author:
description:
  url: https://apache.activemq.org

# Build settings
permalink: none
# permalink: :title/
sass:
  sass_dir: css/

collections:
  artemis_releases:
    output: false
  5x_releases:
    output: true
    permalink: /:name

#  The Current Releases config moved to src/_data/current_releases.yml
#  so 'jekyll serve' picks up edits to it and generates the expected
#  updates (whereas changes to _config.yml are deliberately ignored).

defaults:
  - scope:
      path: "assets/img"
    values:
      image: true
  - scope:
      path: ""
      type: "5x_releases"
    values:
      layout: "5x_release"
      title-class: page-title-activemq5
      type: activemq5

markdown: kramdown
highlighter: rouge
#permalink: /news/:year/:month/:day/:title/
excerpt_separator: ""
source: src
exclude: [ BUILD.md, Gemfile* ]
keep_files: [ .git ]
exclude: [ vendor ]
baseurl:

plugins:
  - jekyll-redirect-from
