# Site settings
title: ActiveMQ
email:
author:
description:
        url: http://apache.activemq.org

# Build settings
permalink: none
# permalink: :title/
sass:
  sass_dir: css/

defaults:
  - scope:
      path: "assets/img"
    values:
      image: true


markdown: kramdown
highlighter: rouge
#permalink: /news/:year/:month/:day/:title/
excerpt_separator: ""
destination: site-content
exclude: [BUILD.md, Gemfile*]
keep_files: [.git]
exclude: [vendor]
baseurl: .
